"""Agent 8 — Email Delivery Agent.

Sends the generated farm plan report to the user via email.
Supports dry-run mode for development (default: dry_run=True).

Configuration via environment variables:
    SMTP_HOST          — SMTP server hostname (default: smtp.gmail.com)
    SMTP_PORT          — SMTP server port (default: 587)
    SMTP_USER          — SMTP username / sender email
    SMTP_PASSWORD      — SMTP password or app-specific password
    SMTP_FROM_NAME     — Display name for sender (default: GrowGrid AI)
    SMTP_USE_TLS       — Use STARTTLS (default: true)
"""

from __future__ import annotations

import json
import logging
import os
import smtplib
from datetime import datetime, timezone
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from typing import Any

from growgrid_core.agents.base_agent import BaseAgent
from growgrid_core.utils.types import (
    PlanRequest,
    ReportPayload,
    ValidatedProfile,
)

logger = logging.getLogger(__name__)


def _escape(text: str) -> str:
    """Basic HTML escaping."""
    return text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")


def _build_html_body(profile: ValidatedProfile, report: ReportPayload) -> str:
    """Build a simple HTML email body from the report payload."""
    sections_html = ""
    for section in report.sections:
        content = section.content
        if isinstance(content, list):
            items = "".join(f"<li>{_escape(str(item))}</li>" for item in content[:20])
            body = f"<ul>{items}</ul>" if items else "<p>No data.</p>"
        elif isinstance(content, dict):
            rows = "".join(
                f"<tr><td style='padding:4px 8px;font-weight:600'>{_escape(str(k))}</td>"
                f"<td style='padding:4px 8px'>{_escape(str(v))}</td></tr>"
                for k, v in content.items()
            )
            body = f"<table style='border-collapse:collapse'>{rows}</table>"
        else:
            body = f"<p>{_escape(str(content))}</p>"

        sections_html += (
            f"<div style='margin-bottom:24px'>"
            f"<h2 style='color:#1e293b;font-size:16px;margin:0 0 8px'>{_escape(section.title)}</h2>"
            f"{body}"
            f"</div>"
        )

    generated_date = report.generated_at[:10] if report.generated_at else "N/A"
    return (
        f"<div style='font-family:system-ui,-apple-system,sans-serif;max-width:640px;margin:0 auto;color:#334155'>"
        f"<div style='background:#0f766e;padding:24px;border-radius:12px 12px 0 0'>"
        f"<h1 style='color:#fff;margin:0;font-size:20px'>GrowGrid AI &mdash; Farm Plan Report</h1>"
        f"</div>"
        f"<div style='background:#fff;padding:24px;border:1px solid #e2e8f0;border-top:none;border-radius:0 0 12px 12px'>"
        f"<div style='background:#f0fdfa;border:1px solid #99f6e4;border-radius:8px;padding:16px;margin-bottom:24px'>"
        f"<p style='margin:0;font-size:14px;color:#0f766e'>{_escape(report.executive_summary)}</p>"
        f"</div>"
        f"{sections_html}"
        f"<hr style='border:none;border-top:1px solid #e2e8f0;margin:24px 0' />"
        f"<p style='color:#94a3b8;font-size:12px;text-align:center'>"
        f"Generated by GrowGrid AI on {generated_date}"
        f"<br/>This is an automated report. Verify recommendations with local agriculture experts."
        f"</p>"
        f"</div>"
        f"</div>"
    )


class EmailDeliveryAgent(BaseAgent):
    """Send plan report via email. Defaults to dry-run mode."""

    def __init__(self, dry_run: bool = True) -> None:
        self._dry_run = dry_run

    def run(self, state: dict[str, Any], request: PlanRequest) -> dict[str, Any]:
        recipient_email = request.email or ""
        profile: ValidatedProfile = state["validated_profile"]
        report: ReportPayload | None = state.get("report_payload")

        if not recipient_email:
            state["email_status"] = {
                "status": "skipped",
                "sent": False,
                "reason": "No email address provided.",
                "dry_run": self._dry_run,
            }
            logger.info("EmailDeliveryAgent: skipped — no email provided.")
            return state

        if not report:
            state["email_status"] = {
                "status": "skipped",
                "sent": False,
                "reason": "No report payload available to send.",
                "dry_run": self._dry_run,
            }
            logger.info("EmailDeliveryAgent: skipped — no report payload.")
            return state

        subject = f"Your GrowGrid Farm Plan — {profile.location}"
        html_body = _build_html_body(profile, report)

        if self._dry_run:
            state["email_status"] = {
                "status": "dry_run",
                "sent": False,
                "to": recipient_email,
                "subject": subject,
                "body_preview": html_body[:500] + "..." if len(html_body) > 500 else html_body,
                "timestamp": datetime.now(timezone.utc).isoformat(),
                "dry_run": True,
                "message": "Email composed but not sent (dry-run mode). "
                "Set dry_run=False and configure SMTP env vars to send.",
            }
            logger.info(
                "EmailDeliveryAgent: dry-run email to %s — subject: %s",
                recipient_email,
                subject,
            )
            return state

        # ── Real send via SMTP ────────────────────────────────────────
        smtp_host = os.getenv("SMTP_HOST", "smtp.gmail.com")
        smtp_port = int(os.getenv("SMTP_PORT", "587"))
        smtp_user = os.getenv("SMTP_USER", "")
        smtp_password = os.getenv("SMTP_PASSWORD", "")
        smtp_from_name = os.getenv("SMTP_FROM_NAME", "GrowGrid AI")
        use_tls = os.getenv("SMTP_USE_TLS", "true").lower() == "true"

        if not smtp_user or not smtp_password:
            state["email_status"] = {
                "status": "error",
                "sent": False,
                "reason": "SMTP_USER or SMTP_PASSWORD not configured.",
                "dry_run": False,
            }
            logger.warning("EmailDeliveryAgent: SMTP credentials not configured.")
            return state

        msg = MIMEMultipart("alternative")
        msg["Subject"] = subject
        msg["From"] = f"{smtp_from_name} <{smtp_user}>"
        msg["To"] = recipient_email

        # Plain text fallback
        text_body = (
            f"GrowGrid AI Farm Plan Report\n\n"
            f"{report.executive_summary}\n\n"
            f"Please view this email in an HTML-capable client for the full report."
        )
        msg.attach(MIMEText(text_body, "plain"))
        msg.attach(MIMEText(html_body, "html"))

        # Attach report as JSON for programmatic use
        report_json = json.dumps(report.model_dump(), indent=2, default=str)
        json_attachment = MIMEText(report_json, "plain")
        json_attachment.add_header(
            "Content-Disposition", "attachment", filename="growgrid_report.json"
        )
        msg.attach(json_attachment)

        try:
            with smtplib.SMTP(smtp_host, smtp_port, timeout=30) as server:
                if use_tls:
                    server.starttls()
                server.login(smtp_user, smtp_password)
                server.send_message(msg)

            state["email_status"] = {
                "status": "sent",
                "sent": True,
                "to": recipient_email,
                "subject": subject,
                "timestamp": datetime.now(timezone.utc).isoformat(),
                "dry_run": False,
            }
            logger.info("EmailDeliveryAgent: sent email to %s.", recipient_email)

        except Exception as exc:
            state["email_status"] = {
                "status": "error",
                "sent": False,
                "to": recipient_email,
                "error": str(exc),
                "timestamp": datetime.now(timezone.utc).isoformat(),
                "dry_run": False,
            }
            logger.exception(
                "EmailDeliveryAgent: failed to send email to %s.", recipient_email
            )

        return state
